version: '3.7'

services:
  server:
    build: .
    restart: always
    command: npm run start:prod
    container_name: pig-server
    ports:
      - 5000:5000
  mongodb:
    image: mongo:4.4
    restart: always
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
