    
name: Automated Version Bump for client
  # You may pin to the exact commit or the version.
  # uses: phips28/gh-action-bump-version@65ec31050fe363c360baaa4fdea37a5dc829d5b0
  uses: phips28/gh-action-bump-version@v8.0.12
  with:
    # Prefix that is used for the git tag
    tag-prefix: v # optional, default is 
    # Words list that trigger a minor version bump
    minor-wording: # optional, default is feat,minor
    # Words list that trigger a major version bump
    major-wording: # optional, default is BREAKING CHANGE,major
    # Words list that trigger a patch version bump
    patch-wording: # optional
    # Words list that trigger a patch version bump
    rc-wording: # optional, default is pre-alpha,pre-beta,pre-rc
    # Avoid to add a TAG to the version update commit
    skip-tag: # optional, default is false
    # Custom dir to the package
    PACKAGEJSON_DIR: client # optional, default is 
