name: Heroku Awake
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: '-s -o /dev/null https://little-pig-bot.herokuapp.com'
