name: Version bump
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: 'Automated Version Bump Server'
        uses: 'phips28/gh-action-bump-version@v8.0.12'
        with:
          PACKAGEJSON_DIR: 'server'
          skip-tag: "true"
        env:
          PACKAGEJSON_DIR: 'server'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Automated Version Bump Client'
        uses: 'phips28/gh-action-bump-version@v8.0.12'
        with:
          PACKAGEJSON_DIR: 'client'
        env:
          PACKAGEJSON_DIR: 'client'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
